---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-storage
  volumeName: pv-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-letsencrypt
  namespace: manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: pv-letsencrypt

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-database
  namespace: manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: pv-database
