apiVersion: v1
kind: Service
metadata:
  name: nginx-service  # neuvo nombre del svbc
  namespace: test  # es el namspeace nuevo
spec:
  selector:
    app: nginx 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
  type: ClusterIP  
